version: "3.4"

services:
  
  dnscollector:
    image: dmachard/go-dnscollector:v0.13.0
    environment:
      - "TZ=Europe/Paris"
    networks:
      - monitoring
    volumes:
      - ${APP_CONFIG}/dnscollector/config.yml:/etc/dnscollector/config.yml
      - ${COLLECTOR_DATA}/:/var/dnscollector/

  dnsdist:
    image: powerdns/dnsdist-17:1.7.0-beta2
    environment:
      - "TZ=Europe/Paris"
    networks:
      - monitoring
    volumes:
      - ${APP_CONFIG}/dnsdist/dnsdist.lua:/etc/dnsdist/conf.d/dnsdist.conf
    ports:
      - mode: host
        protocol: udp
        published: 53
        target: 53
      - mode: host
        protocol: tcp
        published: 53
        target: 53

networks:
  monitoring:
    external: true