global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'docker-manager01'
    static_configs:
      - targets: ['192.168.1.221:9100']
    scrape_interval: 5s

  - job_name: 'docker-manager02'     
    static_configs:
      - targets: ['192.168.1.222:9100']
    scrape_interval: 5s

  - job_name: 'docker-manager03'
    static_configs:
      - targets: ['192.168.1.223:9100']
    scrape_interval: 5s

  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [ http_2xx ]
    relabel_configs:
    - source_labels: [ __address__ ]
      target_label: __param_target
    - source_labels: [ __param_target ]
      target_label: instance
    - target_label: __address__
      replacement: blackbox:9115
    static_configs:
      - targets:
          - https://www.google.com
          - https://www.microsoft.com

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [ http_2xx ]
    relabel_configs:
    - source_labels: [ __address__ ]
      target_label: __param_target
    - source_labels: [ __param_target ]
      target_label: instance
    - target_label: __address__
      replacement: blackbox:9115
    static_configs:
      - targets:
          - https://www.google.com

 - job_name: 'blackbox-dns-monitor'
    scrape_interval: 5s
    metrics_path: /probe
    relabel_configs:
    # add domain name label
    - source_labels: [__address__]
      regex: (.*):.*$
      replacement: $1
      target_label: domain
    # add instance label with dns server IP
    - source_labels: [__address__]
      regex: .*:(.*)$
      replacement: $1
      target_label: instance
    # add module URL parameter with domain name
    - source_labels: [domain]
      target_label: __param_module
    # add target URL parameter with dns server IP
    - source_labels: [instance]
      target_label: __param_target
    # add __address__ with the address of the blackbox exporter to hit
    - target_label: __address__
      replacement: blackbox:9115
      
    static_configs:
      - targets:
        - www.google.com:8.8.8.8
        - www.microsoft.com:8.8.8.8

        - www.google.com:9.9.9.9
        - www.microsoft.com:9.9.9.9
