global:
  scrape_interval:     15s

scrape_configs:
  - job_name: 'docker-manager01'
    static_configs:
      - targets: ['192.168.1.221:9100']
    scrape_interval: 5s

  - job_name: 'docker-manager02'     
    static_configs:
      - targets: ['192.168.1.222:9100']
    scrape_interval: 5s

  - job_name: 'docker-manager03'
    static_configs:
      - targets: ['192.168.1.223:9100']
    scrape_interval: 5s

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [ http_2xx ]
    relabel_configs:
    - source_labels: [ __address__ ]
      target_label: __param_target
    - source_labels: [ __param_target ]
      target_label: instance
    - target_label: __address__
      replacement: blackbox:9115
    static_configs:
      - targets:
          - https://www.google.com
