version: "3.8"

services:
  pdnsrec:
    image: powerdns/pdns-recursor-49
    volumes:
      - ./recursor.lua:/etc/powerdns/recursor.lua
      - ./recursor.conf:/etc/powerdns/recursor.conf
      - ./basic.rpz:/etc/powerdns/basic.rpz
    ports:
      - 5553:53/tcp
      - 5553:53/udp
    restart: unless-stopped