version: "3.8"

services:

  prometheus:
    image: prom/prometheus:v2.31.1
    user: "1000:1000"
    ports:
      - "9090:9090/tcp"
    networks:
      - monitoring
    deploy:
      replicas: 1
    volumes:
      - ${PROMETHEUS_DATA}:/prometheus
      - ${APP_CONFIG}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${APP_CONFIG}/alertmanager/alerts.rules.yml:/alertmanager/alert.rules/alerts.rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=365d'
      - '--web.enable-lifecycle'
    
  grafana:
    image: grafana/grafana:8.2.6
    networks:
      - monitoring
    user: "1000:1000"
    ports:
      - "3000:3000/tcp"
    deploy:
      replicas: 1

    volumes:
      - ${GRAFANA_DATA}:/var/lib/grafana
      - ${APP_CONFIG}/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ${APP_CONFIG}/grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ${APP_CONFIG}/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ${APP_CONFIG}/grafana/dashboards:/var/lib/grafana/dashboards
      
  blackbox:
    image: prom/blackbox-exporter:v0.19.0
    networks:
      - monitoring
    ports:
      - "9115:9115/tcp"
    deploy:
      replicas: 1
      placement:
        constraints:
         - node.labels.monitor == true
    volumes:
    - ${APP_CONFIG}/blackbox/blackbox.yml:/etc/blackbox_exporter/config.yml

  alertmanager:
    image: prom/alertmanager:v0.23.0
    networks:
      - monitoring
    ports:
      - "9093:9093/tcp"
    deploy:
      replicas: 1
    volumes:
      - ${APP_CONFIG}/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--log.level=debug'
      
  loki:
    image: grafana/loki:2.4.0
    user: "1000:1000"
    ports:
      - "3100:3100"
    command: 
     - '--config.file=/etc/loki/config.yaml'
    volumes:
      - ${LOKI_DATA}:/tmp/loki
      - ${APP_CONFIG}/loki/config.yaml:/etc/loki/config.yaml
    networks:
      - monitoring
      
networks:
  monitoring:
    external: true