version: "3.8"

services:
  unbound:
    image: mvance/unbound:1.19.0
    volumes:
      - ./unbound.conf:/opt/unbound/etc/unbound/unbound.conf
      - ./basic.rpz:/opt/unbound/etc/unbound/basic.rpz
    ports:
      - 5553:53/tcp
      - 5553:53/udp
    restart: unless-stopped
