trace:
  verbose: true

collectors:
  dnstap:
    enable: true
    listen-ip: 0.0.0.0
    listen-port: 6000

loggers:
  stdout:
    enable: false  
  logfile:
    enable: true
    file-path:  /var/dnscollector/dnstap.log 
