version: "3.0"

services:
  
  freshrss:
    image: freshrss/freshrss:1.18.1
    volumes:
    - ${DOCKER_DATA}/freshrss-data:/var/www/FreshRSS/data
    - ${DOCKER_DATA}/freshrss-extensions:/var/www/FreshRSS/extensions
    ports:
    - "9090:80/tcp"
    environment:
    - PUID=1000
    - PGID=1000
    - CRON_MIN=4,34
    - TZ=Europe/Paris
    deploy:
      replicas: 1