version: "3.8"

services:
  influxdb:
    image: influxdb:1.8.10
    ports:
      - mode: host
        protocol: tcp
        published: 8086
        target: 8086
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    volumes:
      - ${INFLUXDB_DATA}:/var/lib/influxdb