modules:
  http_2xx:
    prober: http
    timeout: 2s
    http:
      basic_auth:
        username: "******"
        password: "*******"

  www.google.com:
    prober: dns
    timeout: 5s
    dns:
      transport_protocol: "udp"
      preferred_ip_protocol: "ip4"
      query_name: "www.google.com"
      query_type: "A"
      valid_rcodes:
        - NOERROR

  www.microsoft.com:
    prober: dns
    timeout: 5s
    dns:
      transport_protocol: "udp"
      preferred_ip_protocol: "ip4"
      query_name: "www.microsoft.com"
      query_type: "A"
      valid_rcodes:
        - NOERROR
